ALTER TABLE orders ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'PENDING';
UPDATE orders SET status='PENDING' WHERE status IS NULL;
ALTER TABLE orders ALTER COLUMN status SET NOT NULL;
ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'PENDING';
