version: "3.9"

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports: ["8081:8080"]

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports: ["8082:8082"]

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports: ["8083:8083"]

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports: ["8084:8084"]

  order-service:
    build: ./order-service
    container_name: order-service
    ports: ["8085:8085"]

  payment-mock:
    build: ./payment-mock
    container_name: payment-mock
    ports: ["8086:8086"]
